spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/lolstats
spring.datasource.username=lol_user
spring.datasource.password=lol_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

ddragon.base-url=https://ddragon.leagueoflegends.com
ddragon.champion-version=15.10.1
